### ISSUE TITLE
Tempo

### ISSUE THREAD

**Issue by FabioZTessitore** [IannuccilloAntonio/esame_parte_I#1]
La struttura del programma va bene. Ora prova a calcolare ore minuti e secondi

**Comment by IannuccilloAntonio** [comment]
È un poco un problema capire come fare

**Comment by FabioZTessitore** [comment]
Inizia carta e penna

Il 28 giu 2017 10:57 AM, "Antonio Iannuccillo" <notifications@github.com>
ha scritto:

**Comment by IannuccilloAntonio** [comment]
Lo sto facendo, appena faccio qualcosa vi avviso

**Comment by IannuccilloAntonio** [comment]
Ho iniziato a calcolare in quante ore, in quanti minuti e in quanti secondi si consumano tot galloni

**Comment by IannuccilloAntonio** [comment]
Prof, ho finito. Si trova!

**Comment by FabioZTessitore** [comment]
Alla riga 15, puoi usare tempo invece di rifare la divisione. Cmq va bene

**Comment by IannuccilloAntonio** [comment]
Giusto, ho riscritto lo stesso calcolo quando potevo mettere tempo. Ora aggiusto
